# -*- coding: utf-8 -*-
"""W01_Lab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uaP5cZX4hkMEeQD4WIahQAzVqGN8F3QJ

# Week 1 — Lab

**3 hours.** Work through in order. You are not expected to finish everything.

| Part | Time | What |
|---|---|---|
| Warm-up | 15 min | Get set up, fix three broken programs |
| Drills | 60 min | Seven tasks, three tiers |
| Break | 10 min | |
| Mini-project | 75 min | Build your own Record Check |
| Wrap | 20 min | Demo, journal, commit, push |

**Aiming for a pass?** Do the Threshold tasks and the Threshold version of the mini-project.
**Aiming higher?** Threshold and Typical.
**Aiming for a first?** All three, plus the mini-project extension.

---
# Warm-up · 15 min

Your program will fail today. Everyone's does. A red block of text is not the computer
telling you off — it is telling you **where** and **what**.

## How to read it

Python prints the error **last**. Start at the bottom.

```
Traceback (most recent call last):
  File "check.py", line 4, in <module>
    print(value + 1)
          ~~~~~~^~~
TypeError: can only concatenate str (not "int") to str
```

1. **The last line** → the *kind* of problem: `TypeError`
2. **The rest of that line** → the detail: something is text that should be a number
3. **`line 4`** → where to look

That is enough to fix almost every Week 1 error.

| Error | Usually means | First thing to check |
|---|---|---|
| `NameError` | you used a name Python has not seen | spelling, or a capital in the wrong place |
| `TypeError` | text and numbers mixed | did you forget `int()` or `float()`? |
| `ValueError` | right type, impossible value | `int("23.7")` or `float("abc")` |
| `SyntaxError` | Python cannot read the line | quotes, brackets — **check the line above too** |

`SyntaxError` is the odd one: the reported line is often fine and the real problem is an
unclosed bracket or quote on the line before.

## Now do it

Open the `warmup/` folder. Each file is **broken on purpose**. For each one:

1. Run it. Read the last line first.
2. **Write down by hand** what you think is wrong.
3. Fix it. Run it again.

---

> **The rule for this module:** read the last line, look at the line number, try one fix.
> **Then** ask — and when you ask, say what the last line said.
>
> *"It says TypeError on line 4 and I think it's the input"* gets a much faster answer
> than *"it doesn't work"*.
"""

# BROKEN ON PURPOSE.
# Run it, read the last line, then fix it.

record_id = ("R-004")

print(record_id)

# BROKEN ON PURPOSE.
# Run it, read the last line, then fix it.

value = input("Value: ")
print(int(value) + 1)

# BROKEN ON PURPOSE.
# Run it, type 23.7 when asked, read the last line, then fix it.

value = float(input("Value: "))

print(value)

"""---
# Drills

## Threshold

*Aim: get these three working. This is the pass standard.*

### D1. Say hello

Print three lines:

```
==============================
CST1510 - your name
==============================
```

Use `"=" * 30` for the lines, not thirty typed characters.
"""

# D1
print("="*30)
print("CST1510","-","Rithshika")
print("="*30)

"""### D2. Store and report

Store these three values in well-named variables, then print them one per line:

- a record ID of `R-017`
- a value of `41.2`
- a limit of `50`
"""

# D2
record_id = ("R-014")
value = 41.2
limit = 50
print(record_id)
print(value)
print(limit)

"""### D3. Work something out

Using your variables from D2, calculate and print:

- the difference between the value and the limit
- the value as a percentage of the limit

Do not type either answer — calculate both.
"""

# D3
value = 41.2
limit = 50
difference =(limit - value)
percentage = (value/limit)*100
print(f"the difference between the value and the limit:{difference:.2f}")
print(f"the value as a percentage of the limit:{percentage:.2f}%")

"""---
## Typical

*Aim: these use input and formatting.*

### D4. Ask, don't hard-code

Rewrite D2 and D3 so the three values come from `input()` instead of being typed into the code.

Remember what `input()` gives you back.
"""

# D4
record_id =(input("enter your record id:"))
value = float(input("enter your value:"))
limit = float(input("enter your limit:"))


difference =(limit - value:)
percentage = (value/limit)*100

print("The difference between the value and the limit:",difference)
print("The value as a percentage of the limit:",percentage"%")

"""### D5. Make it tidy

Take your D4 output and format it so that:

- every number shows exactly **2 decimal places**
- the numbers are **right-aligned** so the decimal points line up
- the difference always shows its sign (`+3.70` / `-8.80`)
"""

# D5

record_id =(input("enter your record id:"))
value = float((input("enter your value:")))
limit = float(input("enter your limit:"))

difference = (limit - value)
percentage = (value/limit)*100

print(f"The difference between the value and the limit:{difference:>+5.2f}")
print(f"The value as a percentage of the limit:{percentage:>5.2f}%")

"""### D6. Split a number

A process ran for **4831 seconds**.

Using `//` and `%`, print it as:

```
4831 seconds = 1 hours, 20 minutes, 31 seconds
```

Start from the largest unit and work down.
"""

# D6
total_seconds = 4831
hours = total_seconds//3600
remaining = total_seconds%3600
minutes = total_seconds//60
seconds = total_seconds%60
print(total_seconds, "seconds is", hours, "hour", minutes, "minutes and", seconds ,"seconds")

"""---
## Excellent

*Aim: harder, and no step-by-step instructions.*

### D7. Three fields, one calculation

Every percentage question is the same sum. Write **one** program that asks for a *part*, a *total* and a *label*, then prints:

```
rows missing   :  38 of 250  =  15.2 %
```

Test it three times with:

| label | part | total |
|---|---|---|
| `rows missing` | 38 | 250 |
| `failed logins` | 12 | 400 |
| `disk used GB` | 87 | 120 |

The label should be left-aligned in 15 characters so all three line up.
"""

# D7
for i in range(3):
  label = input("enter the label:")
  part = int(input("enter the part:"))
  total = int(input("enter the total:"))
  percentage = (part/total)*100
  print(f"{label:<15} : {part} of {total} = {percentage} %")

"""---
# Mini-project · 80 min

Open **`../LAB/template.py`**. It has the structure already — you fill in the marked sections.

## Choose your lane

Pick **one**. All three are the same program with different words.

| Lane | Your three inputs | Example |
|---|---|---|
| **AI / Data Science** | dataset name, rows loaded, rows expected | `survey_2026`, `1187`, `1200` |
| **Cyber Security** | source IP, failed logins, total attempts | `10.0.0.5`, `12`, `400` |
| **IT** | hostname, GB used, GB total | `srv-01`, `87`, `120` |

## What to build

**Threshold — pass standard.** Ask for the three values, print them back in a bordered report.

```
==================================
  RECORD CHECK  -  srv-01
==================================
  Used        : 87
  Total       : 120
==================================
```

**Typical.** As above, and it *calculates* two things it was not given — the difference,
and the value as a percentage of the total. All numbers show 2 decimal places and are
right-aligned so they line up.

```
==================================
  RECORD CHECK  -  srv-01
==================================
  Used        :      87.00
  Total       :     120.00
  Free        :      33.00
  Percent     :      72.50 %
==================================
```

**Excellent.** As above, plus the difference always shows its sign, one extra calculated
line of your own that is genuinely useful for your lane (with a comment saying **why**),
and variable names that read clearly without needing a comment.

## Rules

- **Do not type any number you could calculate.**
- Convert every value the user gives you to the right type.
- **No `if` statements** — that is next week. If you want one, write that in your journal and move on.

## When it works

1. Run it three times with different inputs. Does it still look right?
2. Run it with a total of `0`. Write the error down — **do not fix it**. That is Week 2.
3. Show it to the person next to you.

MINI PROJECT
"""

#Name  :RITHSHIKA
#Lane  :  AI
#Date  :25-09-2026

host_name = input("Enter your hostname:")
total =float(input("Enter the total gb:"))
used = float(input("Enter  the gb used:"))

free = (total-used)
percent= (used/total)*100
free_percent = (free/total)*100
#I calculated free percentage to know how much gb is available

print("="*35)
print(f"  RECORD CHECK - {host_name}")
print("="*35)
print(f"  Used           :  {used:.2f}")
print(f"  Total          :  {total:.2f}")
print(f"  Free           :  {free:+.2f}")
print(f"  Percent        :  {percent:.2f}%")
print(f"  free percent   :  {free_percent:.2f}%")
print("="*35)

"""---
# Wrap · 20 min

## 1. Demo — 2 minutes each

Run your mini-project for the person next to you. Then they run theirs for you.

## 2. Journal — handwritten, on paper · 10 min

Do **a)**, **b)**, **d)** and **e)** below on paper, by hand — they are for you, not
submitted. Not typed, not copied from the slides — writing it by hand is the point.
Only **c)**, the Cheat Sheet box, gets photographed and pasted into the **Journal**
cell at the very end of this notebook.

**a) Draw it.** The four boxes, from memory. Label which one we built this week and
name two things that live in it.

**b) Explain it** — one or two sentences each, without looking anything up:
- What does `input()` always give you back, and why does that matter?
- What is the difference between `"20"` and `20`?
- What does `%` do, and when would you use it?

**c) Cheat Sheet — Box 1.** This is a permanent page, not a disposable table — rule a
sheet into 12 numbered boxes today (3 or 4 per row, one box per week for the rest of
term) and bring the *same sheet* to every lab from here on. Do not copy this from a
slide or an `examples/` file — run each line yourself before you write it down.

```
Box 1 — INPUT & OUTPUT

print("...", "...")       commas add a space
"=" * 30                    a separator
name = value                   (= "gets")
type(x)  -> str / int / float
input("...")  always text
int(x) / float(x)               convert
f"{x:.2f}"  f"{x:>10}"      format
```

Try it yourself — run `137 // 60` and `137 % 60` with your own two numbers instead,
and write down what you actually got: ________________

Note: *(the one error from section (d) that stung most today, in your own words)*

Photograph the Cheat Sheet page and paste it into the **Journal** cell at the end of
this notebook — the only photo you submit this week, showing Box 1 filled. You will
paste this same page again every week, with one more box each time.

**d) My errors.** Every error you hit today — its **name**, what it turned out to mean,
and what you changed.

**e) Still fuzzy** — one sentence. One thing from today that hasn't clicked yet.

> Keep every week's Cheat Sheet photo — see the CW1 specification for what's submitted and when.

## 3. Git — 5 minutes

In VS Code's terminal, inside your module folder:

```
git add .
git commit -m "Week 1 lab and mini-project"
git push
```

Then open your repository on GitHub in a browser and check your files are there.
If you see nothing, you are in the wrong folder — `pwd` tells you where you are.

| Command | Plain English |
|---|---|
| `git add .` | mark everything here as ready to save |
| `git commit -m "..."` | save a snapshot, with a note saying what changed |
| `git push` | send it to GitHub |

> `"Week 1 lab and mini-project"` tells you something. `"stuff"` does not.
> You will be reading these messages again before the coursework deadline.

---
# What to keep

Nothing is marked this week. Everything is kept.

| Item | Where |
|---|---|
| this notebook, with your answers and the pasted-in Cheat Sheet photo | your repository |
| your mini-project `.py` | your repository |

That's it — **2 files**. (The warm-up fixes are worth doing, but aren't required to
be pushed or kept — `git add .` may sweep them in too, and that's fine, they just
aren't checked.)

These accumulate into **CW1** — see the CW1 specification for what's submitted and when.

## If you are stuck

1. Read the **last line** of the error.
2. Check the *Common mistakes* table in that topic's walkthrough.
3. Run the matching file in that topic's `examples/`.
4. Ask — and say what the last line of the error said.

---
# Journal — paste your Cheat Sheet photo here

Click into this cell, then paste the photo directly (`Cmd+V` / `Ctrl+V` after
copying it, or drag the image file in). Jupyter embeds a pasted or dropped image in
the notebook itself — nothing else to do, no separate file to track.

**The Cheat Sheet page**, showing Box 1 filled in:

*(paste here)*
"""